version: 2

jobs:
  suite:
    docker:
      - image: haskell:8.6.5
    steps:
      - checkout
      - run:
          command: apt update
      - run:
          command: apt install -y libpcre3-dev
      - run:
          command: cabal new-update
      - run:
          command: cabal new-build
      - run:
          command: cabal new-test
      - run:
          command: 'echo "symlink-bindir: /" >> /root/.cabal/config'
      - run:
          command: cabal new-install exe:LaTeX-numbers
      - store_artifacts:
          path: /LaTeX-numbers
      - persist_to_workspace:
          root: dist-newstyle/build/x86_64-linux/ghc-8.6.5/LaTeX-numbers-0.1.0.0/x/LaTeX-numbers/build/LaTeX-numbers
          paths:
            - LaTeX-numbers
  deploy:
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: dist-newstyle/build/x86_64-linux/ghc-8.6.5/LaTeX-numbers-0.1.0.0/x/LaTeX-numbers/build/LaTeX-numbers
      - run:
          command: scp dist-newstyle/build/x86_64-linux/ghc-8.6.5/LaTeX-numbers-0.1.0.0/x/LaTeX-numbers/build/LaTeX-numbers/LaTeX-numbers $USER@$HOST:~
      - run:
          command: ssh -t $USER@$HOST "chmod +x LaTeX-numbers"
      - run:
          command: ssh -t $USER@$HOST "./update_notify.sh $CIRCLE_BUILD_NUM \"LaTeX-numbers\""

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - suite
      - deploy:
          requires:
            - suite
          filters:
            branches:
              only: master
